// Core types for XLN v1 - Pure functional, immutable data structures

// --- Core Naming Convention ---
// Server*: The highest level of abstraction (The Post Office).
// Entity*: The business logic container (The Company).
// Tx: An atomic, state-changing operation (An Agenda Item).
// Input: A command or message to a machine (A Memo).
// Block: A finalized set of transactions.

// A transaction at the highest level, routed by the server.
// Analogy: A package arriving at the Post Office.
export type ServerTx = {
  readonly signerIndex: number;
  readonly entityId: string;
  readonly input: EntityInput;
};

// A command directed at a specific Entity machine.
// Analogy: A memo sent to a specific Company.
export type EntityInput =
  | { readonly kind: 'addTx'; readonly tx: EntityTx }
  | { readonly kind: 'importState'; readonly state: EntityState }
  | { readonly kind: 'proposeBlock' } // Proposer asks to form a block from its mempool
  | { readonly kind: 'confirmBlock'; readonly block: EntityBlock }; // A signer confirms a proposed block

// An atomic, state-changing operation within an Entity.
// Analogy: A single agenda item in the memo.
export type EntityTx = {
  readonly op: string; // e.g., 'MINT', 'DELEGATE_QUORUM'
  readonly data: unknown;
};

// A finalized set of transactions with quorum signatures.
// Analogy: The official, signed Minutes of a Board Meeting.
export type EntityBlock = {
  readonly height: number;
  readonly txs: readonly EntityTx[];
  readonly hash: string;
  readonly signatures: Record<number, string>; // signerIndex -> signature (placeholder)
};

// The complete, self-contained state of a single Entity replica.
// Analogy: A Company's full set of records.
export type EntityState = {
  readonly entityId: string; // The entity's unique identifier
  readonly height: number; // The block height of this entity
  readonly data: unknown; // The actual business state (e.g., { balance: 1000 })
  readonly mempool: readonly EntityTx[]; // Pending transactions for the next block
  readonly proposedBlock?: EntityBlock; // A block awaiting confirmation
  readonly quorum: readonly number[]; // List of signer indices participating in this entity
  readonly proposerIndex: number; // The signer who proposes blocks (usually quorum[0])
};

// A message generated by one Entity to be sent to another.
// Analogy: A memo placed in the 'To-Do' tray.
export type OutboxMessage = {
  readonly fromEntityId: string;
  readonly toEntityId: string;
  readonly toSignerIndex: number; // The proposer of the target entity
  readonly payload: EntityInput;
};

// The entire state of the server simulation.
// Analogy: The state of the entire Post Office building.
export type ServerState = {
  readonly height: number; // The server's block height
  // Nested map: signerIndex -> entityId -> EntityState
  readonly signers: ReadonlyMap<number, ReadonlyMap<string, EntityState>>;
  readonly mempool: readonly ServerTx[];
};

// A finalized server block containing all processed transactions.
// Analogy: The daily log of all packages processed by the Post Office.
export type ServerBlock = {
  readonly height: number;
  readonly txs: readonly ServerTx[];
  readonly timestamp: number;
};

// Entity registry entry for global entity discovery.
// Analogy: The public directory listing of all companies.
export type EntityInfo = {
  readonly entityId: string;
  readonly quorum: readonly number[];
  readonly proposerIndex: number;
  readonly metadata?: unknown; // Public profile data
};